mmcdole/gofeed

README.md
atom/parser.go
atom/parser_test.go
feedparser.go
feedparser_test.go
rss/parser.go
rss/parser_test.go
translator.go
translator_test.go

Moved to using `io.Reader` instead of strings by default to prevent having to have the entire feed in memory while we are parsing it.
Also made some minor modifications to the Translator interface.
This should hopefully fully address #14

io.Reader All The Things!  

---

README.md

For clarity, imports the required modules, and fixes typos.
[ci skip]

doc(README): improve "Advance Usage" README section

---

atom/parser.go
internal/shared/parseutils.go
rss/parser.go

This should solve #38 where an illformed feed had random text between tags in an item.  These will now be skipped/ignored.

Ignore tokens between start/end tags

---

atom/parser.go
internal/shared/parseutils.go
internal/shared/parseutils_test.go

Fix #64.
With this patch, `DecodeEntities` now decodes both predefined entities and numeric character references. I had to make a few small changes since the function can now fail if it contains invalid entities.
I also added tests for the function.

add support for numeric character reference in character data

---

internal/shared/charsetconv.go

This removes the unused but imported package fmt. Currently this throws the
error `imported and not used: "fmt"`.
Thanks!

Remove unused pkg fmt

---

parser.go

I'm using gofeed to constantly poll some Atom/RSS feeds. There was a memory leak in my project caused by HTTP responses in this library not being closed: I was using `ParseURL`. It turns out any non 2xx response was leaking, because `Close()` was not being called on it.
This PR fixes this and also closes responses even if there was a non-nil error. The presence of an `err` does not mean an absence of `resp`, as redirection failures will produce both `err` and `resp` as non-nil.

Remember to close non-2xx responses

---

README.md
translator.go

Discovered this flaw when using Slashdot's RSS feed as an example during development. The only Published date is a DC extension.
Example RSS URL: http://rss.slashdot.org/Slashdot/slashdotMain

Adds support for publish date in Dublin Core.

---

internal/shared/extparser.go
rss/feed.go
rss/parser.go
translator.go

When content is available in a `<content:encoded></content:encoded>` tag, parse it as the item's `Content` field.
We understand it's a highly demanded feature, and we also need it in one of our projects, so we thought we'd implement it.

Add support for content:encoded

---

extensions/itunes.go

Looks like this was accidentally omitted.

get keywords from iTunes extensions

---

parser.go

It will allow the applications using this library to introspect this error easily

Set the feed type detection error in a public variable

---

parser.go

I changed the .Get() call to .Do() here for a header insertion
This is a cheap edit, but I've discovered that on GETs the User-Agent is being sent blank.  This is a problem for RSS feeds from Reddit, as Reddit will send back phony 429s  (Rate Limit) responses because the User-Agent is not "valid".   Might want to expose this further if people need to imitate a User-Agent to get around a server-side restriction.

Add a User-Agent header to ParseURL()

---

parser.go

http.NewRequest error return should be check.
If there is an error during NewRequest (I've experimented it), req is nil and segfault occurs during req.Header.Set()

parser.go / Bug fix

---

atom/parser.go
detector.go
internal/shared/parseutils.go
internal/shared/parseutils_test.go
rss/parser.go
translator.go

- adds a share function to strip CDATA tags with decoding of entities outside of the tags
- adds a basic test
Open questions:
- not sure if it's a standard way to parse CDATA. Any ideas?
- anything else that this affects?

Better support for CDATA

---

extensions/itunes.go

Added episode, season and episodeType fields to Itunes item. 
Fields taken from official [Itunes documentation.](https://help.apple.com/itc/podcasts_connect)

Add additional itunes item extensions

---

.gitignore
parser.go
parser_test.go

`ParseURLWithContext` method is added to support cancel or timing out for http requests.

Context support is added for ParseURL

---

testdata/translator/rss/feed_link_-_rss_channel_atom_link.json
testdata/translator/rss/feed_link_-_rss_channel_atom_link.xml
translator.go

For the DefaultRSSTranslator the FeedLink field should get its value from the /rss/channel/atom:link[@rel="self"]/@href tag.

Fix: get gofeed.FeedLink from atom:link tag

---

internal/shared/parseutils.go
internal/shared/parseutils_test.go

I've encounter few feeds with html entities in <title> or <description> for ex.
`<title>Site d&#8217;actualit&eacute; g&eacute;n&eacute;raliste</title>`
Instead of clean UTF8:
`<title>Site d’actualité généraliste</title>`
Even if it's not a valid XML, it's quite easy to be tolerant, and not reject the feed.

Allow unknown html entities

---

testdata/translator/atom/feed_item_updated_-_atom03_feed_entry_modified.json
translator.go

When an atom item only have updated field, use it to fill published.
- Less function is using published field, it has to always been
populated.
- Simplify code when using both RSS and Atom feeds.
This fix #146

Force published field

---

rss/feed.go
rss/parser.go
testdata/parser/rss/rss_channel_item_custom.json
testdata/parser/rss/rss_channel_item_custom.xml
testdata/translator/rss/feed_item_category_-_rss_channel_item_custom.json
testdata/translator/rss/feed_item_category_-_rss_channel_item_custom.xml
translator.go

I have a requirement to parse elements that are not part of the standard spec.  Noticed someone also recently raised this as part of the issue #174
Raising this pull request in case this will be helpful for others.

Ability to parse custom fields in rss that are not part of the spec

---

.gitignore
go.mod
rss/feed.go
rss/parser.go
testdata/parser/rss/issue_36_enclosure_text.json
testdata/parser/rss/rss_channel_item_enclosure.json
testdata/translator/rss/feed_item_enclosure_-_rss_channel_item_enclosure.json
testdata/translator/rss/feed_item_enclosures_-_rss_channel_item_enclosures.json
testdata/translator/rss/feed_item_enclosures_-_rss_channel_item_enclosures.xml
translator.go

Multiple enclosures in RSS are not handled.
Rather we get the last one.
1. Added Multiple enclosure handling to RSS and translator.
2. Updated test data.
3. Added specific test coverage for multiple enclosures.
Note: since the RSS parser seemed to accumulate the last enclosure,
and select that one. I reversed the accumulation array, so that,
anyone expecting the old behavior would not be surprised.

ISSUE 189 - Multiple enclosures in rss

---

parser.go

Directly set the context instead of (implicitly) setting `context.Background` and then do a copy with the intended context.
Rationale: The implementation of `http.NewRequest`
```go
func NewRequest(method, url string, body io.Reader) (*Request, error) {
return NewRequestWithContext(context.Background(), method, url, body)
}
```

Use `http.NewRequestWithContext` directly.

---

README.md

The spaces were very distracting trying to read the readme. Perhaps someone used an over aggressive markdown formatter. :)

Remove spaces from go identifiers in readme

---

testdata/parser/rss/issue_217_enclosure_children.json
testdata/parser/rss/issue_217_enclosure_children.xml
translator.go

Fix #217 
Ignore all child node of <enclosure>, not only TextNodes.

Fix RSS enclosure parsing

---

testdata/translator/atom/feed_image_-_atom10_feed_icon.json
testdata/translator/atom/feed_image_-_atom10_feed_icon.xml
translator.go

First off, fantastic library! :clap:  Great job.
While integrating it into [Feeder](https://github.com/spacecowboy/feeder) (my Android feed reader) one of my unit tests failed. :disappointed: 
This PR would make the test pass in my project. What do you think?
For reference, it is this assertion: https://github.com/spacecowboy/Feeder/blob/master/app/src/test/java/com/nononsenseapps/feeder/model/FeedParserTest.kt#L673
Which parses the file at: https://github.com/spacecowboy/Feeder/blob/master/app/src/test/resources/com/nononsenseapps/feeder/model/atom_cowboy.xml

Added fallback to atom icon when atom logo is missing

---

extensions/extensions_test.go
testdata/extensions/media/feed_image_-_rss_channel_media.json
testdata/extensions/media/feed_image_-_rss_channel_media.xml
testdata/extensions/media/feed_item_image_-_rss_channel_item_media.json
testdata/extensions/media/feed_item_image_-_rss_channel_item_media.xml
testdata/translator/rss/feed_image_-_rss_channel_description.json
testdata/translator/rss/feed_image_-_rss_channel_description.xml
testdata/translator/rss/feed_item_enclosure_-_rss_channel_item_enclosure.json
testdata/translator/rss/feed_item_image_-_rss_channel_item_content.json
testdata/translator/rss/feed_item_image_-_rss_channel_item_content.xml
testdata/translator/rss/feed_item_image_-_rss_channel_item_description.json
testdata/translator/rss/feed_item_image_-_rss_channel_item_description.xml
translator.go

Additional locations where images are attempted to be extracted:
* media:content extension https://www.rssboard.org/media-rss#media-content
* The first `<img>` in content or description
Fixes #133

Extract feed and item images from more places

---

internal/shared/extparser.go
rss/parser.go
testdata/parser/rss/rss_channel_item_content_encoded.json
testdata/parser/rss/rss_channel_item_content_encoded.xml
testdata/translator/rss/feed_item_image_-_rss_channel_item_content.xml

PR #220 introduced a failing test for detecting images in the "content" element. It should instead be testing the "content:encoded" element. But that uncovered an issue with how extensions were being detected (the "content" namespace was being detected as an extension element).
As a more robust way of checking for the "content" namespace, this PR exposes `shared.PrefixForNamspace()` as a public function so it can be used in the RSS parser. This should also fix PR #211 (and includes @JLugagne's test case from that PR).
Once the fixes to xml:base handling in #222 are merged, this should fix the remaining failing test reported in #210.

Fix handling of RSS content:encoded

---

atom/parser.go
go.mod
go.sum
internal/shared/xmlbase.go

The issue is that goxpp's DecodeElement() pop's the BaseStack after unmarshaling an element -- as it should to keep the BaseStack in sync with the current document scope. But that means the atom parser needs to keep a reference to the current base before calling DecodeElement() so that it can correctly resolve URLs.
Without this fix, elements with xml:base attributes will be erroneously resolved with the parent xml:base.
This fix is a little awkward with all of its saving and restoring of BaseStacks. A simpler solution would be to simply get the `xml:base` attribute from the decoded element and resolve against that. However, that would require changes to `goxpp`: either change `XmlBaseResolveUrl()` to accept a string rather than acting as a method, or maybe adding a separate …

Atom: use correct xml:base for decoded elements

---

internal/shared/xmlbase.go
testdata/parser/rss/rss_channel_item_uri_at_protocol.json
testdata/parser/rss/rss_channel_item_uri_at_protocol.xml

Continue processing when URI attribute resolution fails instead of halting the entire feed parse. This allows feeds containing AT Protocol URIs, mailto: links, and other non-HTTP schemes to parse successfully.
Fixes #236

Fix parsing failure with non-HTTP URI schemes

---

atom/parser.go
extension_helpers.go
extension_helpers_test.go
feed.go
parser_test.go
rss/feed.go
rss/parser.go
testdata/parser/atom/atom10_feed_custom_elements.json
testdata/parser/atom/atom10_feed_custom_elements.xml
testdata/parser/atom/atom10_feed_entry_custom_elements.json
testdata/parser/atom/atom10_feed_entry_custom_elements.xml
testdata/parser/atom/atom10_feed_entry_custom_multiple.json
testdata/parser/atom/atom10_feed_entry_custom_multiple.xml
testdata/parser/rss/rss_channel_custom_elements.json
testdata/parser/rss/rss_channel_custom_elements.xml
testdata/parser/rss/rss_channel_item_custom.json
testdata/parser/rss/rss_channel_item_custom_and_extension.json
testdata/parser/rss/rss_channel_item_custom_and_extension.xml
testdata/parser/rss/rss_channel_item_custom_cdata.json
testdata/parser/rss/rss_channel_item_custom_cdata.xml
testdata/parser/rss/rss_channel_item_custom_multiple.json
testdata/parser/rss/rss_channel_item_custom_multiple.xml
testdata/parser/rss/rss_channel_item_custom_with_attrs.json
testdata/parser/rss/rss_channel_item_custom_with_attrs.xml
testdata/translator/rss/feed_item_category_-_rss_channel_item_custom.json
translator.go
translator_test.go

This PR removes the `Item.Custom` field entirely and enhances the existing `Extensions` field to handle all custom and non-standard elements with full structural support including attributes and nested elements. **Custom element support has been added to both RSS and Atom parsers.**
- Remove `Custom` field from `gofeed.Feed` and `gofeed.Item` structs
- Remove `Custom` field from `rss.Item` struct  
- Update RSS parser to add non-namespaced elements to `Extensions` under "_custom" namespace
- Update Atom parser to add non-namespaced elements to `Extensions` under "_custom" namespace
- Add support for custom elements at both channel/feed and item/entry level in both formats
- Add convenient helper methods for accessing extensions
- Fix RSS parser to properly handle RDF structural elements
- …

v2: Remove Custom field and enhance Extensions for custom elements
